name: Notify Telegram on eventi.csv update

on:
  push:
    paths:
      - 'eventi.csv'
  schedule:
    - cron: '0 8 * * *' # Esegue ogni giorno alle 08:00 UTC

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Telegram notification
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT: ${{ secrets.TELEGRAM_CHAT_ID }}
          SITE_URL: https://vivafest.github.io/ticket-affiliate
        run: |
          MESSAGE="🎫 Eventi aggiornati su Ticket Affiliate Hub! %0A👉 $SITE_URL"
          curl -s -X POST "https://api.telegram.org/bot${TELEGRAM_TOKEN}/sendMessage" \
            -d chat_id="${TELEGRAM_CHAT}" \
            -d text="$MESSAGE" \
            -d parse_mode="HTML"
